// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: l2.proto

package l2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LinkStatus int32

const (
	LinkStatus_DOWN    LinkStatus = 0
	LinkStatus_UP      LinkStatus = 1
	LinkStatus_MISSING LinkStatus = 2
)

// Enum value maps for LinkStatus.
var (
	LinkStatus_name = map[int32]string{
		0: "DOWN",
		1: "UP",
		2: "MISSING",
	}
	LinkStatus_value = map[string]int32{
		"DOWN":    0,
		"UP":      1,
		"MISSING": 2,
	}
)

func (x LinkStatus) Enum() *LinkStatus {
	p := new(LinkStatus)
	*p = x
	return p
}

func (x LinkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_l2_proto_enumTypes[0].Descriptor()
}

func (LinkStatus) Type() protoreflect.EnumType {
	return &file_l2_proto_enumTypes[0]
}

func (x LinkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkStatus.Descriptor instead.
func (LinkStatus) EnumDescriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{0}
}

type StackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId int32 `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
}

func (x *StackRequest) Reset() {
	*x = StackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackRequest) ProtoMessage() {}

func (x *StackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackRequest.ProtoReflect.Descriptor instead.
func (*StackRequest) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{0}
}

func (x *StackRequest) GetVpcId() int32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

type Stack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId           int32  `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	BridgeLinkName  string `protobuf:"bytes,2,opt,name=bridge_link_name,json=bridgeLinkName,proto3" json:"bridge_link_name,omitempty"`
	BridgeLinkIndex int32  `protobuf:"varint,3,opt,name=bridge_link_index,json=bridgeLinkIndex,proto3" json:"bridge_link_index,omitempty"`
}

func (x *Stack) Reset() {
	*x = Stack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stack) ProtoMessage() {}

func (x *Stack) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stack.ProtoReflect.Descriptor instead.
func (*Stack) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{1}
}

func (x *Stack) GetVpcId() int32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *Stack) GetBridgeLinkName() string {
	if x != nil {
		return x.BridgeLinkName
	}
	return ""
}

func (x *Stack) GetBridgeLinkIndex() int32 {
	if x != nil {
		return x.BridgeLinkIndex
	}
	return 0
}

type StackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stack  *Stack               `protobuf:"bytes,1,opt,name=stack,proto3" json:"stack,omitempty"`
	Status *StackStatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StackResponse) Reset() {
	*x = StackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackResponse) ProtoMessage() {}

func (x *StackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackResponse.ProtoReflect.Descriptor instead.
func (*StackResponse) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{2}
}

func (x *StackResponse) GetStack() *Stack {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *StackResponse) GetStatus() *StackStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type StackStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bridge    LinkStatus `protobuf:"varint,1,opt,name=bridge,proto3,enum=vpc.l2.LinkStatus" json:"bridge,omitempty"`
	Transport LinkStatus `protobuf:"varint,2,opt,name=transport,proto3,enum=vpc.l2.LinkStatus" json:"transport,omitempty"`
}

func (x *StackStatusResponse) Reset() {
	*x = StackStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackStatusResponse) ProtoMessage() {}

func (x *StackStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackStatusResponse.ProtoReflect.Descriptor instead.
func (*StackStatusResponse) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{3}
}

func (x *StackStatusResponse) GetBridge() LinkStatus {
	if x != nil {
		return x.Bridge
	}
	return LinkStatus_DOWN
}

func (x *StackStatusResponse) GetTransport() LinkStatus {
	if x != nil {
		return x.Transport
	}
	return LinkStatus_DOWN
}

type StackChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId  int32                `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Action string               `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Status *StackStatusResponse `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StackChange) Reset() {
	*x = StackChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StackChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackChange) ProtoMessage() {}

func (x *StackChange) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackChange.ProtoReflect.Descriptor instead.
func (*StackChange) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{4}
}

func (x *StackChange) GetVpcId() int32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *StackChange) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StackChange) GetStatus() *StackStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

type NicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId         int32    `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Id            string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SubnetVlanId  uint32   `protobuf:"varint,3,opt,name=subnet_vlan_id,json=subnetVlanId,proto3" json:"subnet_vlan_id,omitempty"`
	ManuallyAdded bool     `protobuf:"varint,4,opt,name=manually_added,json=manuallyAdded,proto3" json:"manually_added,omitempty"`
	ManualHwaddr  string   `protobuf:"bytes,5,opt,name=manual_hwaddr,json=manualHwaddr,proto3" json:"manual_hwaddr,omitempty"`
	Ip            []string `protobuf:"bytes,6,rep,name=ip,proto3" json:"ip,omitempty"`
}

func (x *NicRequest) Reset() {
	*x = NicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicRequest) ProtoMessage() {}

func (x *NicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicRequest.ProtoReflect.Descriptor instead.
func (*NicRequest) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{5}
}

func (x *NicRequest) GetVpcId() int32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *NicRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NicRequest) GetSubnetVlanId() uint32 {
	if x != nil {
		return x.SubnetVlanId
	}
	return 0
}

func (x *NicRequest) GetManuallyAdded() bool {
	if x != nil {
		return x.ManuallyAdded
	}
	return false
}

func (x *NicRequest) GetManualHwaddr() string {
	if x != nil {
		return x.ManualHwaddr
	}
	return ""
}

func (x *NicRequest) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

type Nic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId  int32    `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Hwaddr string   `protobuf:"bytes,2,opt,name=hwaddr,proto3" json:"hwaddr,omitempty"`
	Id     string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name   string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Index  int32    `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Vlan   uint32   `protobuf:"varint,6,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Ip     []string `protobuf:"bytes,7,rep,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Nic) Reset() {
	*x = Nic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nic.ProtoReflect.Descriptor instead.
func (*Nic) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{6}
}

func (x *Nic) GetVpcId() int32 {
	if x != nil {
		return x.VpcId
	}
	return 0
}

func (x *Nic) GetHwaddr() string {
	if x != nil {
		return x.Hwaddr
	}
	return ""
}

func (x *Nic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Nic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nic) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Nic) GetVlan() uint32 {
	if x != nil {
		return x.Vlan
	}
	return 0
}

func (x *Nic) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

type NicStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status LinkStatus `protobuf:"varint,1,opt,name=status,proto3,enum=vpc.l2.LinkStatus" json:"status,omitempty"`
}

func (x *NicStatusResponse) Reset() {
	*x = NicStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NicStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicStatusResponse) ProtoMessage() {}

func (x *NicStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicStatusResponse.ProtoReflect.Descriptor instead.
func (*NicStatusResponse) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{7}
}

func (x *NicStatusResponse) GetStatus() LinkStatus {
	if x != nil {
		return x.Status
	}
	return LinkStatus_DOWN
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_l2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_l2_proto_rawDescGZIP(), []int{8}
}

var File_l2_proto protoreflect.FileDescriptor

var file_l2_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6c, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x76, 0x70, 0x63, 0x2e,
	0x6c, 0x32, 0x22, 0x25, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x5f, 0x6c, 0x69,
	0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x69, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53,
	0x74, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x73, 0x0a, 0x13, 0x53, 0x74,
	0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x30, 0x0a,
	0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x71, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x70, 0x63, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x0a, 0x4e, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x5f, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x56, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79,
	0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x5f,
	0x68, 0x77, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61,
	0x6e, 0x75, 0x61, 0x6c, 0x48, 0x77, 0x61, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x92, 0x01, 0x0a, 0x03, 0x4e,
	0x69, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x70, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x77, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x77, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x76,
	0x6c, 0x61, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x3f, 0x0a, 0x11, 0x4e, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x2b, 0x0a, 0x0a, 0x4c, 0x69, 0x6e,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x32, 0xc1, 0x03, 0x0a, 0x09, 0x4c, 0x32, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x63, 0x6b,
	0x12, 0x14, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e,
	0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x2e, 0x76, 0x70,
	0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x74,
	0x61, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x2e, 0x76, 0x70, 0x63, 0x2e,
	0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x2e,
	0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x57, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x73, 0x12, 0x0d, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x13, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x63,
	0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x06, 0x41,
	0x64, 0x64, 0x4e, 0x49, 0x43, 0x12, 0x12, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4e,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x76, 0x70, 0x63, 0x2e,
	0x6c, 0x32, 0x2e, 0x4e, 0x69, 0x63, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4e, 0x49, 0x43, 0x12, 0x0b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4e,
	0x69, 0x63, 0x1a, 0x0d, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x4e, 0x49, 0x43, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x2e, 0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4e, 0x69, 0x63, 0x1a, 0x19, 0x2e,
	0x76, 0x70, 0x63, 0x2e, 0x6c, 0x32, 0x2e, 0x4e, 0x69, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x6c, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l2_proto_rawDescOnce sync.Once
	file_l2_proto_rawDescData = file_l2_proto_rawDesc
)

func file_l2_proto_rawDescGZIP() []byte {
	file_l2_proto_rawDescOnce.Do(func() {
		file_l2_proto_rawDescData = protoimpl.X.CompressGZIP(file_l2_proto_rawDescData)
	})
	return file_l2_proto_rawDescData
}

var file_l2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_l2_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_l2_proto_goTypes = []interface{}{
	(LinkStatus)(0),             // 0: vpc.l2.LinkStatus
	(*StackRequest)(nil),        // 1: vpc.l2.StackRequest
	(*Stack)(nil),               // 2: vpc.l2.Stack
	(*StackResponse)(nil),       // 3: vpc.l2.StackResponse
	(*StackStatusResponse)(nil), // 4: vpc.l2.StackStatusResponse
	(*StackChange)(nil),         // 5: vpc.l2.StackChange
	(*NicRequest)(nil),          // 6: vpc.l2.NicRequest
	(*Nic)(nil),                 // 7: vpc.l2.Nic
	(*NicStatusResponse)(nil),   // 8: vpc.l2.NicStatusResponse
	(*Empty)(nil),               // 9: vpc.l2.Empty
}
var file_l2_proto_depIdxs = []int32{
	2,  // 0: vpc.l2.StackResponse.stack:type_name -> vpc.l2.Stack
	4,  // 1: vpc.l2.StackResponse.status:type_name -> vpc.l2.StackStatusResponse
	0,  // 2: vpc.l2.StackStatusResponse.bridge:type_name -> vpc.l2.LinkStatus
	0,  // 3: vpc.l2.StackStatusResponse.transport:type_name -> vpc.l2.LinkStatus
	4,  // 4: vpc.l2.StackChange.status:type_name -> vpc.l2.StackStatusResponse
	0,  // 5: vpc.l2.NicStatusResponse.status:type_name -> vpc.l2.LinkStatus
	1,  // 6: vpc.l2.L2Service.AddStack:input_type -> vpc.l2.StackRequest
	1,  // 7: vpc.l2.L2Service.GetStack:input_type -> vpc.l2.StackRequest
	1,  // 8: vpc.l2.L2Service.StackStatus:input_type -> vpc.l2.StackRequest
	1,  // 9: vpc.l2.L2Service.DeleteStack:input_type -> vpc.l2.StackRequest
	9,  // 10: vpc.l2.L2Service.WatchStacks:input_type -> vpc.l2.Empty
	6,  // 11: vpc.l2.L2Service.AddNIC:input_type -> vpc.l2.NicRequest
	7,  // 12: vpc.l2.L2Service.DeleteNIC:input_type -> vpc.l2.Nic
	7,  // 13: vpc.l2.L2Service.NICStatus:input_type -> vpc.l2.Nic
	3,  // 14: vpc.l2.L2Service.AddStack:output_type -> vpc.l2.StackResponse
	3,  // 15: vpc.l2.L2Service.GetStack:output_type -> vpc.l2.StackResponse
	4,  // 16: vpc.l2.L2Service.StackStatus:output_type -> vpc.l2.StackStatusResponse
	9,  // 17: vpc.l2.L2Service.DeleteStack:output_type -> vpc.l2.Empty
	5,  // 18: vpc.l2.L2Service.WatchStacks:output_type -> vpc.l2.StackChange
	7,  // 19: vpc.l2.L2Service.AddNIC:output_type -> vpc.l2.Nic
	9,  // 20: vpc.l2.L2Service.DeleteNIC:output_type -> vpc.l2.Empty
	8,  // 21: vpc.l2.L2Service.NICStatus:output_type -> vpc.l2.NicStatusResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_l2_proto_init() }
func file_l2_proto_init() {
	if File_l2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StackChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NicStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_l2_proto_goTypes,
		DependencyIndexes: file_l2_proto_depIdxs,
		EnumInfos:         file_l2_proto_enumTypes,
		MessageInfos:      file_l2_proto_msgTypes,
	}.Build()
	File_l2_proto = out.File
	file_l2_proto_rawDesc = nil
	file_l2_proto_goTypes = nil
	file_l2_proto_depIdxs = nil
}
