// Code generated by protoc-gen-go. DO NOT EDIT.
// source: l2.proto

package vpc_l2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LinkStatus int32

const (
	LinkStatus_DOWN    LinkStatus = 0
	LinkStatus_UP      LinkStatus = 1
	LinkStatus_MISSING LinkStatus = 2
)

var LinkStatus_name = map[int32]string{
	0: "DOWN",
	1: "UP",
	2: "MISSING",
}

var LinkStatus_value = map[string]int32{
	"DOWN":    0,
	"UP":      1,
	"MISSING": 2,
}

func (x LinkStatus) String() string {
	return proto.EnumName(LinkStatus_name, int32(x))
}

func (LinkStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{0}
}

type StackRequest struct {
	VpcId                int32    `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackRequest) Reset()         { *m = StackRequest{} }
func (m *StackRequest) String() string { return proto.CompactTextString(m) }
func (*StackRequest) ProtoMessage()    {}
func (*StackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{0}
}

func (m *StackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackRequest.Unmarshal(m, b)
}
func (m *StackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackRequest.Marshal(b, m, deterministic)
}
func (m *StackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackRequest.Merge(m, src)
}
func (m *StackRequest) XXX_Size() int {
	return xxx_messageInfo_StackRequest.Size(m)
}
func (m *StackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StackRequest proto.InternalMessageInfo

func (m *StackRequest) GetVpcId() int32 {
	if m != nil {
		return m.VpcId
	}
	return 0
}

type Stack struct {
	VpcID                int32    `protobuf:"varint,1,opt,name=vpcID,proto3" json:"vpcID,omitempty"`
	BridgeLinkName       string   `protobuf:"bytes,2,opt,name=bridge_link_name,json=bridgeLinkName,proto3" json:"bridge_link_name,omitempty"`
	BridgeLinkIndex      int32    `protobuf:"varint,3,opt,name=bridge_link_index,json=bridgeLinkIndex,proto3" json:"bridge_link_index,omitempty"`
	VtepLinkName         string   `protobuf:"bytes,4,opt,name=vtep_link_name,json=vtepLinkName,proto3" json:"vtep_link_name,omitempty"`
	VtepLinkIndex        int32    `protobuf:"varint,5,opt,name=vtep_link_index,json=vtepLinkIndex,proto3" json:"vtep_link_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stack) Reset()         { *m = Stack{} }
func (m *Stack) String() string { return proto.CompactTextString(m) }
func (*Stack) ProtoMessage()    {}
func (*Stack) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{1}
}

func (m *Stack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stack.Unmarshal(m, b)
}
func (m *Stack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stack.Marshal(b, m, deterministic)
}
func (m *Stack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stack.Merge(m, src)
}
func (m *Stack) XXX_Size() int {
	return xxx_messageInfo_Stack.Size(m)
}
func (m *Stack) XXX_DiscardUnknown() {
	xxx_messageInfo_Stack.DiscardUnknown(m)
}

var xxx_messageInfo_Stack proto.InternalMessageInfo

func (m *Stack) GetVpcID() int32 {
	if m != nil {
		return m.VpcID
	}
	return 0
}

func (m *Stack) GetBridgeLinkName() string {
	if m != nil {
		return m.BridgeLinkName
	}
	return ""
}

func (m *Stack) GetBridgeLinkIndex() int32 {
	if m != nil {
		return m.BridgeLinkIndex
	}
	return 0
}

func (m *Stack) GetVtepLinkName() string {
	if m != nil {
		return m.VtepLinkName
	}
	return ""
}

func (m *Stack) GetVtepLinkIndex() int32 {
	if m != nil {
		return m.VtepLinkIndex
	}
	return 0
}

type StackResponse struct {
	Stack                *Stack               `protobuf:"bytes,1,opt,name=stack,proto3" json:"stack,omitempty"`
	Status               *StackStatusResponse `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StackResponse) Reset()         { *m = StackResponse{} }
func (m *StackResponse) String() string { return proto.CompactTextString(m) }
func (*StackResponse) ProtoMessage()    {}
func (*StackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{2}
}

func (m *StackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackResponse.Unmarshal(m, b)
}
func (m *StackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackResponse.Marshal(b, m, deterministic)
}
func (m *StackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackResponse.Merge(m, src)
}
func (m *StackResponse) XXX_Size() int {
	return xxx_messageInfo_StackResponse.Size(m)
}
func (m *StackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StackResponse proto.InternalMessageInfo

func (m *StackResponse) GetStack() *Stack {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *StackResponse) GetStatus() *StackStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

type StackStatusResponse struct {
	Bridge               LinkStatus `protobuf:"varint,1,opt,name=bridge,proto3,enum=vpc.l2.LinkStatus" json:"bridge,omitempty"`
	Vtep                 LinkStatus `protobuf:"varint,2,opt,name=vtep,proto3,enum=vpc.l2.LinkStatus" json:"vtep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StackStatusResponse) Reset()         { *m = StackStatusResponse{} }
func (m *StackStatusResponse) String() string { return proto.CompactTextString(m) }
func (*StackStatusResponse) ProtoMessage()    {}
func (*StackStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{3}
}

func (m *StackStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackStatusResponse.Unmarshal(m, b)
}
func (m *StackStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackStatusResponse.Marshal(b, m, deterministic)
}
func (m *StackStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackStatusResponse.Merge(m, src)
}
func (m *StackStatusResponse) XXX_Size() int {
	return xxx_messageInfo_StackStatusResponse.Size(m)
}
func (m *StackStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StackStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StackStatusResponse proto.InternalMessageInfo

func (m *StackStatusResponse) GetBridge() LinkStatus {
	if m != nil {
		return m.Bridge
	}
	return LinkStatus_DOWN
}

func (m *StackStatusResponse) GetVtep() LinkStatus {
	if m != nil {
		return m.Vtep
	}
	return LinkStatus_DOWN
}

type StackChange struct {
	VpcId                int32                `protobuf:"varint,1,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	Action               string               `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Status               *StackStatusResponse `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StackChange) Reset()         { *m = StackChange{} }
func (m *StackChange) String() string { return proto.CompactTextString(m) }
func (*StackChange) ProtoMessage()    {}
func (*StackChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{4}
}

func (m *StackChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackChange.Unmarshal(m, b)
}
func (m *StackChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackChange.Marshal(b, m, deterministic)
}
func (m *StackChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackChange.Merge(m, src)
}
func (m *StackChange) XXX_Size() int {
	return xxx_messageInfo_StackChange.Size(m)
}
func (m *StackChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StackChange.DiscardUnknown(m)
}

var xxx_messageInfo_StackChange proto.InternalMessageInfo

func (m *StackChange) GetVpcId() int32 {
	if m != nil {
		return m.VpcId
	}
	return 0
}

func (m *StackChange) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *StackChange) GetStatus() *StackStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f692411d37028fef, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("vpc.l2.LinkStatus", LinkStatus_name, LinkStatus_value)
	proto.RegisterType((*StackRequest)(nil), "vpc.l2.StackRequest")
	proto.RegisterType((*Stack)(nil), "vpc.l2.Stack")
	proto.RegisterType((*StackResponse)(nil), "vpc.l2.StackResponse")
	proto.RegisterType((*StackStatusResponse)(nil), "vpc.l2.StackStatusResponse")
	proto.RegisterType((*StackChange)(nil), "vpc.l2.StackChange")
	proto.RegisterType((*Empty)(nil), "vpc.l2.Empty")
}

func init() { proto.RegisterFile("l2.proto", fileDescriptor_f692411d37028fef) }

var fileDescriptor_f692411d37028fef = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xed, 0x34, 0x76, 0xd3, 0x71, 0x93, 0x86, 0x29, 0x45, 0x51, 0xb9, 0x54, 0x0b, 0x54,
	0x51, 0x90, 0x22, 0xe4, 0xc2, 0x81, 0x23, 0x60, 0x54, 0x59, 0x2a, 0x01, 0xd9, 0x42, 0x3d, 0x46,
	0xae, 0xbd, 0x6a, 0x57, 0x71, 0x6c, 0x37, 0xde, 0x5a, 0xf0, 0x5a, 0xbc, 0x01, 0x6f, 0x86, 0x3c,
	0xbb, 0x69, 0x6c, 0x14, 0x2a, 0xd4, 0xa3, 0xe7, 0xff, 0xf6, 0xdf, 0xf9, 0x67, 0xc7, 0xd0, 0x4b,
	0xdd, 0x69, 0xb1, 0xca, 0x65, 0x8e, 0x76, 0x55, 0xc4, 0xd3, 0xd4, 0x65, 0xaf, 0x60, 0x3f, 0x94,
	0x51, 0xbc, 0x08, 0xf8, 0xed, 0x1d, 0x2f, 0x25, 0x1e, 0x41, 0xad, 0xcc, 0x45, 0x32, 0x32, 0x4f,
	0xcc, 0xb1, 0x15, 0x58, 0x55, 0x11, 0xfb, 0x09, 0xfb, 0x6d, 0x82, 0x45, 0x1c, 0x3e, 0x05, 0x2a,
	0x79, 0x4d, 0xdd, 0xc3, 0x31, 0x0c, 0xaf, 0x56, 0x22, 0xb9, 0xe6, 0xf3, 0x54, 0x64, 0x8b, 0x79,
	0x16, 0x2d, 0xf9, 0xa8, 0x73, 0x62, 0x8e, 0xf7, 0x82, 0x81, 0xaa, 0x5f, 0x88, 0x6c, 0x31, 0x8b,
	0x96, 0x1c, 0x27, 0xf0, 0xa4, 0x49, 0x8a, 0x2c, 0xe1, 0x3f, 0x46, 0x3b, 0xe4, 0x75, 0xb0, 0x41,
	0xfd, 0xba, 0x8c, 0x2f, 0x61, 0x50, 0x49, 0x5e, 0x34, 0x3c, 0xbb, 0xe4, 0xb9, 0x5f, 0x57, 0xef,
	0x1d, 0x4f, 0xe1, 0x60, 0x43, 0x29, 0x3f, 0x8b, 0xfc, 0xfa, 0x6b, 0x8c, 0xdc, 0x98, 0x80, 0xbe,
	0x8e, 0x5a, 0x16, 0x79, 0x56, 0x72, 0x7c, 0x01, 0x56, 0x59, 0x17, 0x28, 0x8a, 0xe3, 0xf6, 0xa7,
	0x6a, 0x26, 0x53, 0x45, 0x29, 0x0d, 0xcf, 0xc0, 0x2e, 0x65, 0x24, 0xef, 0x4a, 0xca, 0xe3, 0xb8,
	0xcf, 0x5b, 0x54, 0x48, 0xd2, 0xda, 0x31, 0xd0, 0x28, 0x13, 0x70, 0xb8, 0x45, 0xc6, 0x09, 0xd8,
	0x2a, 0x22, 0xdd, 0x38, 0x70, 0x71, 0xed, 0x55, 0x37, 0xa9, 0x59, 0x4d, 0xe0, 0x29, 0x74, 0xeb,
	0xf6, 0xe9, 0xd6, 0xed, 0x24, 0xe9, 0xec, 0x16, 0x1c, 0xba, 0xea, 0xd3, 0x4d, 0x94, 0x5d, 0xf3,
	0x7f, 0xbc, 0x1f, 0x3e, 0x03, 0x3b, 0x8a, 0xa5, 0xc8, 0x33, 0xfd, 0x2a, 0xfa, 0xab, 0x91, 0x6e,
	0xe7, 0xff, 0xd3, 0xed, 0x82, 0xf5, 0x79, 0x59, 0xc8, 0x9f, 0x93, 0xd7, 0x00, 0x9b, 0x7e, 0xb0,
	0x07, 0x5d, 0xef, 0xeb, 0xe5, 0x6c, 0x68, 0xa0, 0x0d, 0x9d, 0xef, 0xdf, 0x86, 0x26, 0x3a, 0xb0,
	0xfb, 0xc5, 0x0f, 0x43, 0x7f, 0x76, 0x3e, 0xec, 0xb8, 0xbf, 0x3a, 0xb0, 0x77, 0xe1, 0x86, 0x7c,
	0x55, 0x89, 0x98, 0xe3, 0x7b, 0xe8, 0x7d, 0x48, 0x12, 0xbd, 0x52, 0xed, 0xc1, 0xab, 0x4d, 0x3c,
	0x3e, 0xfa, 0xab, 0xaa, 0x9a, 0x60, 0x46, 0x7d, 0xf4, 0x9c, 0xcb, 0x47, 0x1d, 0xfd, 0xa8, 0x87,
	0xa5, 0x3b, 0xde, 0x7e, 0xfa, 0xa1, 0x19, 0x30, 0x03, 0xdf, 0x82, 0xe3, 0xf1, 0x94, 0x4b, 0xfe,
	0x50, 0x07, 0xf7, 0xbb, 0x44, 0x83, 0x62, 0x06, 0xbe, 0x03, 0xe7, 0x32, 0x92, 0xf1, 0x0d, 0x51,
	0x25, 0xb6, 0xf5, 0xe3, 0xc3, 0x96, 0x89, 0x7a, 0x4a, 0x66, 0xbc, 0x31, 0xaf, 0x6c, 0xfa, 0x5b,
	0xcf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x57, 0x9d, 0xef, 0xc4, 0xb9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// L2ServiceClient is the client API for L2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type L2ServiceClient interface {
	AddStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackResponse, error)
	GetStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackResponse, error)
	StackStatus(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackStatusResponse, error)
	DeleteStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*Empty, error)
	WatchStacks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (L2Service_WatchStacksClient, error)
}

type l2ServiceClient struct {
	cc *grpc.ClientConn
}

func NewL2ServiceClient(cc *grpc.ClientConn) L2ServiceClient {
	return &l2ServiceClient{cc}
}

func (c *l2ServiceClient) AddStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackResponse, error) {
	out := new(StackResponse)
	err := c.cc.Invoke(ctx, "/vpc.l2.L2Service/AddStack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l2ServiceClient) GetStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackResponse, error) {
	out := new(StackResponse)
	err := c.cc.Invoke(ctx, "/vpc.l2.L2Service/GetStack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l2ServiceClient) StackStatus(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackStatusResponse, error) {
	out := new(StackStatusResponse)
	err := c.cc.Invoke(ctx, "/vpc.l2.L2Service/StackStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l2ServiceClient) DeleteStack(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/vpc.l2.L2Service/DeleteStack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l2ServiceClient) WatchStacks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (L2Service_WatchStacksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_L2Service_serviceDesc.Streams[0], "/vpc.l2.L2Service/WatchStacks", opts...)
	if err != nil {
		return nil, err
	}
	x := &l2ServiceWatchStacksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type L2Service_WatchStacksClient interface {
	Recv() (*StackChange, error)
	grpc.ClientStream
}

type l2ServiceWatchStacksClient struct {
	grpc.ClientStream
}

func (x *l2ServiceWatchStacksClient) Recv() (*StackChange, error) {
	m := new(StackChange)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// L2ServiceServer is the server API for L2Service service.
type L2ServiceServer interface {
	AddStack(context.Context, *StackRequest) (*StackResponse, error)
	GetStack(context.Context, *StackRequest) (*StackResponse, error)
	StackStatus(context.Context, *StackRequest) (*StackStatusResponse, error)
	DeleteStack(context.Context, *StackRequest) (*Empty, error)
	WatchStacks(*Empty, L2Service_WatchStacksServer) error
}

// UnimplementedL2ServiceServer can be embedded to have forward compatible implementations.
type UnimplementedL2ServiceServer struct {
}

func (*UnimplementedL2ServiceServer) AddStack(ctx context.Context, req *StackRequest) (*StackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStack not implemented")
}
func (*UnimplementedL2ServiceServer) GetStack(ctx context.Context, req *StackRequest) (*StackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStack not implemented")
}
func (*UnimplementedL2ServiceServer) StackStatus(ctx context.Context, req *StackRequest) (*StackStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StackStatus not implemented")
}
func (*UnimplementedL2ServiceServer) DeleteStack(ctx context.Context, req *StackRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStack not implemented")
}
func (*UnimplementedL2ServiceServer) WatchStacks(req *Empty, srv L2Service_WatchStacksServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStacks not implemented")
}

func RegisterL2ServiceServer(s *grpc.Server, srv L2ServiceServer) {
	s.RegisterService(&_L2Service_serviceDesc, srv)
}

func _L2Service_AddStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L2ServiceServer).AddStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpc.l2.L2Service/AddStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L2ServiceServer).AddStack(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L2Service_GetStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L2ServiceServer).GetStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpc.l2.L2Service/GetStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L2ServiceServer).GetStack(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L2Service_StackStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L2ServiceServer).StackStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpc.l2.L2Service/StackStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L2ServiceServer).StackStatus(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L2Service_DeleteStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L2ServiceServer).DeleteStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vpc.l2.L2Service/DeleteStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L2ServiceServer).DeleteStack(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L2Service_WatchStacks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(L2ServiceServer).WatchStacks(m, &l2ServiceWatchStacksServer{stream})
}

type L2Service_WatchStacksServer interface {
	Send(*StackChange) error
	grpc.ServerStream
}

type l2ServiceWatchStacksServer struct {
	grpc.ServerStream
}

func (x *l2ServiceWatchStacksServer) Send(m *StackChange) error {
	return x.ServerStream.SendMsg(m)
}

var _L2Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vpc.l2.L2Service",
	HandlerType: (*L2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStack",
			Handler:    _L2Service_AddStack_Handler,
		},
		{
			MethodName: "GetStack",
			Handler:    _L2Service_GetStack_Handler,
		},
		{
			MethodName: "StackStatus",
			Handler:    _L2Service_StackStatus_Handler,
		},
		{
			MethodName: "DeleteStack",
			Handler:    _L2Service_DeleteStack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStacks",
			Handler:       _L2Service_WatchStacks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "l2.proto",
}
